{{- if .Values.ingressRoute.enabled -}}
{{- $fullName := include "tiwengo.fullname" . -}}
{{- $host := .Values.ingressRoute.host -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $fullName }}-http
  labels:
    {{- include "tiwengo.labels" . | nindent 4 }}
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`{{ $host }}`)
      services:
        - name: {{ $fullName }}
          port: 6080
{{- if .Values.ingressRoute.tls.enabled }}
      middlewares:
        - name: https-only
          namespace: kube-system
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $fullName }}-https
  labels:
    {{- include "tiwengo.labels" . | nindent 4 }}
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`{{ $host }}`)
      services:
        - name: {{ $fullName }}
          port: 6080
      middlewares:
        - name: cors
          namespace: kube-system
        - name: hsts
          namespace: kube-system
  tls:
    certResolver: {{ .Values.ingressRoute.tls.certResolver }}
{{- end -}}
{{- end }}
