apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tiwengo.fullname" . }}
type: Opaque
data:
  TOKEN_SECRET: {{ .Values.secret.tokenSecret | b64enc }}
  DB_USERNAME: {{ .Values.secret.db.username | b64enc }}
  DB_PASSWORD: {{ .Values.secret.db.password | b64enc }}
  SMS_UID: {{ .Values.secret.sms.uid | b64enc }}
  SMS_PWD: {{ .Values.secret.sms.pwd | b64enc }}
