apiVersion: v1
kind: Service
metadata:
  name: {{ include "tiwengo.fullname" . }}
  labels:
    {{- include "tiwengo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: external
      port: 6080
      targetPort: external
      protocol: TCP
    - name: internal
      port: 9000
      targetPort: internal
      protocol: TCP
  selector:
    {{- include "tiwengo.selectorLabels" . | nindent 4 }}
