apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "identity.fullname" . }}
  labels:
    {{- include "identity.labels" . | nindent 4 }}
data:
  config.yaml: |-
{{- with .Values.configs  }}
{{- toYaml . | nindent 4 }}
{{- end }}
