apiVersion: v2
name: identity
description: manage user authentication and authorization
type: application
version: 0.1.0
appVersion: "v0.1.1"
keywords:
  - identity
home: https://identity.linyc.idv.tw/
sources:
  - https://github.com/mirror520/identity
maintainers:
  - name: Lin, Ying-Chin
    email: mirror770109@gmail.com
